version: '3.9'

networks:
  default:

volumes:
  dbdata:

services:
  SQLServer:
    image: mcr.microsoft.com/mssql/server:2019-latest
    container_name: local-db
    user: "0:0"
    env_file:
      - sql-server.env
    ports:
      - 1433:1433
    volumes:
      - dbdata:/var/opt/mssql/data
    networks:
      - default